- name: "如果/etc/ssh/sshd_config存在 \"# Port\" 则修改ssh监听端口"
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: "^# Port "
    line: "Port {{varNewSshPort}}"

- name: "如果/etc/ssh/sshd_config存在 \"Port \""
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: "^Port "
    line: "Port {{varNewSshPort}}"

- name: "重启sshd服务"
  systemd:
    name: sshd
    state: restarted
