- name: "yum install -y chrony"
  yum:
    name: chrony
    state: installed
- name: "systemctl enable chronyd and systemctl start chronyd"
  systemd:
    name: chronyd
    state: restarted
    enabled: yes