- name: "从https://bucketxy.oss-cn-hangzhou.aliyuncs.com/jmeter/apache-jmeter-5.4.1.tgz下载Jmeter"
  get_url:
    url: https://bucketxy.oss-cn-hangzhou.aliyuncs.com/jmeter/apache-jmeter-5.4.1.tgz
    dest: /tmp/apache-jmeter-5.4.1.tgz
    checksum: md5:ea44a5ff72c25069e6c4b76467292899

- name: "判断是否已安装Jmeter"
  stat: path=/usr/local/jmeter
  register: jmeter_folder

- name: "rm -rf /tmp/apache-jmeter-5.4.1"
  file:
    path: /tmp/apache-jmeter-5.4.1
    state: absent
  when: not jmeter_folder.stat.exists

- name: "tar -xvzf apache-jmeter-5.4.1.tgz"
  shell: cd /tmp && tar -xvzf apache-jmeter-5.4.1.tgz
  when: not jmeter_folder.stat.exists
- name: "mv /tmp/apache-jmeter-5.4.1 /usr/local/jmeter"
  shell: mv /tmp/apache-jmeter-5.4.1 /usr/local/jmeter
  when: not jmeter_folder.stat.exists

- name: "修改#server.rmi.ssl.disable=false为server.rmi.ssl.disable=true"
  lineinfile:
    path: /usr/local/jmeter/bin/jmeter.properties
    regexp: "#server.rmi.ssl.disable="
    line: "server.rmi.ssl.disable=true"
    insertbefore: "# resolve links"

- name: "master模式修改jmeter.properties remote_hosts=配置"
  lineinfile:
    path: /usr/local/jmeter/bin/jmeter.properties
    regexp: "^remote_hosts="
    line: "remote_hosts={{ varRemoteHosts }}"
  when: varMasterMode is defined and varMasterMode and varRemoteHosts is defined and varRemoteHosts|length > 0

- name: "修改堆内存-Xmx"
  lineinfile:
    path: /usr/local/jmeter/bin/jmeter
    regexp: "HEAP="
    line: "HEAP=\"-Xms1g -Xmx{{ var_heap_mx }}g\""
    insertbefore: "# resolve links"

- name: "配置jmeter-service.service"
  template:
    src: jmeter-server.service
    dest: /usr/lib/systemd/system/jmeter-server.service
  when: var_slave_mode is defined and var_slave_mode

- name: "systemctl daemon-reload"
  shell: systemctl daemon-reload

- name: "systemctl start jmeter-server"
  systemd:
    name: jmeter-server
    state: restarted
    enabled: yes
  when: var_slave_mode is defined and var_slave_mode