- name: "Download jmeter from url https://bucketxy.oss-cn-hangzhou.aliyuncs.com/jmeter/apache-jmeter-5.4.1.tgz"
  get_url:
    url: https://bucketxy.oss-cn-hangzhou.aliyuncs.com/jmeter/apache-jmeter-5.4.1.tgz
    dest: /tmp/apache-jmeter-5.4.1.tgz
    checksum: md5:ea44a5ff72c25069e6c4b76467292899
- name: "Check if jmeter already installed"
  stat: path=/usr/local/jmeter
  register: jmeter_folder
- name: "rm -rf /tmp/apache-jmeter-5.4.1"
  file:
    path: /tmp/apache-jmeter-5.4.1
    state: absent
  when: not jmeter_folder.stat.exists
- name: "tar -xvzf apache-jmeter-5.4.1.tgz"
  shell: cd /tmp && tar -xvzf apache-jmeter-5.4.1.tgz
  when: not jmeter_folder.stat.exists
- name: "mv /tmp/apache-jmeter-5.4.1 /usr/local/jmeter"
  shell: mv /tmp/apache-jmeter-5.4.1 /usr/local/jmeter
  when: not jmeter_folder.stat.exists