- name: "安装和配置kubernetes"
  hosts: all
  become: yes
  roles:
    - role: role_centos_eol
    - role: role_os_firewall
    - role: role_os_selinux
    - role: role_os_timezone
    - role: role_os_swap_config
    - role: role_docker_install
    - role: role_k8s_install
