---
- name: Install elasticsearch server
  hosts: all
  become: yes
  roles:
    - role: role_os_timezone
    - role: role_os_firewall
    - role: role_jdk_install
    - role: role_elasticsearch_install