---
#- name: "安装openresty"
#  hosts: localhost
#  vars_prompt:
#    - name: "var_host_deploy"
#      prompt: "输入部署openresty主机（例如：192.168.1.20:33890）："
#      private: no
#  pre_tasks:
#    - add_host: name="{{ var_host_deploy }}" groups=host_deploy
#
#- hosts: host_deploy
#  become: yes
#  roles:
#    - role: role_os_firewall
#    - role: role_os_selinux
#    - role: role_os_timezone
#    - role: role_openresty_install

- name: "安装openresty"
  hosts: all
  become: yes
  roles:
    - role: role_centos_eol
    - role: role_os_firewall
    - role: role_os_selinux
    - role: role_os_timezone
    - role: role_openresty_install