---
- name: "安装awscli"
  hosts: all
  become: yes
  roles:
    - role: role_centos_eol
    - role: role_os_timezone
    - role: role_os_firewall
    - role: role_os_selinux
    - role: role_os_chrony
    - role: role_awscli_config