---
- name: "Install kamailio standalone server"
  hosts: all
  become: yes
  vars_files:
    - role_kamailio_install/vars.yml
  vars_prompt:
    - name: "var_kamailio_listen_port"
      prompt: "Enter kamailio listen port"
      default: 5098
      private: no
  roles:
    - role: role_os_timezone
    - role: role_kamailio_install