---
- name: "安装zookeeper"
  hosts: all
  become: yes
  roles:
    - role: role_centos_eol
    - role: role_os_timezone
    - role: role_os_firewall
    - role: role_os_chrony
    - role: role_jdk_install
    - role: role_zookeeper_install