---

#- name: "编译openresty"
#  hosts: localhost
#  vars_prompt:
#    - name: "var_host_compile"
#      prompt: "输入编译openresty主机IP（例如：192.168.1.20:33890）："
#      private: no
#  pre_tasks:
#    - add_host: name="{{ var_host_compile }}" groups=host_compile
#
#- hosts: host_compile
#  become: yes
#  roles:
#    - role: role_openresty_compile

- name: "编译openresty"
  hosts: all
  become: yes
  roles:
    - role: role_openresty_compile