# 每5天的 01:12 重启一次
- name: "创建kgx-facadea重启任务"
  cron:
    name: "kgx-facadea-restart-task"
    job: "cd /data/workspace-git/kgx-docker/service-facadea && docker-compose restart kgx-facadea && docker-compose restart kgx-facadea-openresty"
    minute: "12"
    hour: "1"
    day: "*/5"

- name: "创建kgx-facadez重启任务"
  cron:
    name: "kgx-facadez-restart-task"
    job: "cd /data/workspace-git/kgx-docker/service-facadez && docker-compose restart kgx-facadez && docker-compose restart kgx-facadez-openresty"
    minute: "12"
    hour: "1"
    day: "*/5"

- name: "创建kgx-facaded重启任务"
  cron:
    name: "kgx-facaded-restart-task"
    job: "cd /data/workspace-git/kgx-docker/service-facaded && docker-compose restart kgx-facaded && docker-compose restart kgx-facaded-openresty"
    minute: "12"
    hour: "1"
    day: "*/5"

- name: "创建kgx-datanode-client重启任务"
  cron:
    name: "kgx-datanode-client-restart-task"
    job: "cd /data/workspace-git/kgx-docker/service-datanode && docker-compose restart kgx-datanode-client"
    minute: "12"
    hour: "1"
    day: "*/5"

- name: "创建kgx-management-client重启任务"
  cron:
    name: "kgx-management-client-restart-task"
    job: "cd /data/workspace-git/kgx-docker/service-management && docker-compose restart kgx-management-client"
    minute: "12"
    hour: "1"
    day: "*/5"