- name: "判断操作支持的操作系统"
  assert:
    that:
      - (ansible_distribution == "CentOS" and ansible_distribution_major_version == "8")
    fail_msg: "docker目前只支持centOS8系统安装"

- package_facts:
   manager: auto
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

- name: "复制locustfile.py"
  copy:
    src: locustfile.py
    dest: /usr/local/locustfile.py

- name: "复制docker-compose-master.yml"
  template:
    src: docker-compose-master.yml
    dest: /usr/local/docker-compose.yml
  when: mode_master | default(False) | bool

- name: "复制docker-compose-slave.yml"
  template:
    src: docker-compose-slave.yml
    dest: /usr/local/docker-compose.yml
  when: mode_slave | default(False) | bool

- name: "使用docker-compose命令重启master服务"
  shell: cd /usr/local && docker-compose down && docker-compose up -d
  when: mode_master | default(False) | bool

- name: "使用docker-compose命令重启slave服务"
  shell: cd /usr/local && docker-compose down && docker-compose up -d
  when: mode_slave | default(False) | bool