- name: "判断操作支持的操作系统"
  assert:
    that:
#      - ansible_distribution == "CentOS" and (ansible_distribution_major_version == "7" or ansible_distribution_major_version == "8")
      - ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"
    fail_msg: "k8s目前只支持centOS8系统部署"

- name: "设置主机名称"
  shell: hostnamectl set-hostname {{ varHostname }}
  when: varSetHostname is defined and varSetHostname|bool

- name: "master节点配置/etc/hosts"
  lineinfile:
    path: /etc/hosts
    regexp: "{{ varHostIp }} {{ varHostname }}"
    line: "{{ varHostIp }} {{ varHostname }}"
  when: varMasterNode is defined and varMasterNode|bool and varHostname is defined and varHostname|length>0

- name: "配置kubernetes yum源"
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    force: yes

- name: "使用yum安装kubelet-1.20.0、kubeadm-1.20.0、kubectl-1.20.0"
  yum:
    name: kubelet-1.20.0,kubeadm-1.20.0,kubectl-1.20.0
    state: installed

- name: "systemctl enable kubelet"
  systemd:
    name: kubelet
    enabled: yes

- name: "检测端口10250是否打开用于判断kubeadm init命令是否已执行过"
  wait_for:
    port: 10250
    delay: 0
    timeout: 5
    msg: "port 10250 is not listening"
  register: port_10250_checking
  ignore_errors: yes
- name: "master节点kubeadm init"
  shell: >
    kubeadm init
    --apiserver-advertise-address={{ varHostIp }}
    --image-repository registry.aliyuncs.com/google_containers
    --kubernetes-version v1.20.0
    --service-cidr=10.1.0.0/16
    --pod-network-cidr=10.244.0.0/16
  when: varMasterNode is defined and varMasterNode|bool and port_10250_checking.failed == true

- name: "master节点配置kubectl命令运行环境"
  shell: |
    mkdir -p $HOME/.kube
    sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config
  when: varMasterNode is defined and varMasterNode|bool

#- name: "复制calico.yaml到$HOME/calico.yaml"
#  copy:
#    src: calico.yaml
#    dest: $HOME/calico.yaml
#    force: yes
#  when: varMasterNode is defined and varMasterNode|bool
#- name: "master节点启动calico"
#  shell: kubectl apply -f $HOME/calico.yaml
#  when: varMasterNode is defined and varMasterNode|bool

- name: "复制kube-flannel.yml到$HOME/kube-flannel.yml"
  copy:
    src: kube-flannel.yml
    dest: $HOME/kube-flannel.yml
    force: yes
  when: varMasterNode is defined and varMasterNode|bool
- name: "master节点启动flannel"
  shell: kubectl apply -f $HOME/kube-flannel.yml
  when: varMasterNode is defined and varMasterNode|bool and port_10250_checking.failed == true