---
# 安装配置maven
- name: 下载maven
  get_url:
   url: https://bucketxyh.oss-cn-hongkong.aliyuncs.com/maven/apache-maven-3.5.4-bin.tar.gz
   dest: /tmp/apache-maven-3.5.4-bin.tar.gz
   checksum: md5:89eea39183139e5f8a0c1601d495b3b6

- name: 解压maven
  shell: tar -xvzf /tmp/apache-maven-3.5.4-bin.tar.gz -C /tmp
- name: 移动maven到/usr/local目录
  shell: mv -n /tmp/apache-maven-3.5.4 /usr/local

# 配置centOS maven环境变量
- name: 检查~/.bash_profile是否已配置maven环境变量
  shell: cat ~/.bash_profile | grep 'export PATH=$PATH:/usr/local/apache-maven-3.5.4/bin' | wc -l
  register: var_grep_result
  when: ansible_distribution=="CentOS"
- name: 配置~/.bash_profile maven环境变量
  lineinfile:
   path: ~/.bash_profile
   line: 'export PATH=$PATH:/usr/local/apache-maven-3.5.4/bin'
  when: ansible_distribution=="CentOS" and var_grep_result.stdout == "0"

# 配置ubuntu maven
- name: "复制文件初始化maven环境变量maven.sh到/etc/profile.d/maven.sh"
  copy:
    src: maven.sh
    dest: /etc/profile.d/maven.sh
    force: no
  when: ansible_distribution == "Ubuntu"

# 配置centOS maven jvm 内存
- name: "检查centOS是否已配置maven jvm内存"
  shell: cat ~/.bash_profile | grep 'export MAVEN_OPTS="-Xmx1024m"' | wc -l
  register: var_grep_result
  when: ansible_distribution=="CentOS"
- lineinfile:
   path: ~/.bash_profile
   line: 'export MAVEN_OPTS="-Xmx1024m"'
  when: ansible_distribution=="CentOS" and var_grep_result.stdout == "0"