---
# ubuntu安装vscode
- name: "下载vscode程序"
  get_url:
    url: https://bucketxyh.oss-cn-hongkong.aliyuncs.com/vscode/code-stable-x64-1694670691.tar.gz
    dest: /tmp/code-stable-x64-1694670691.tar.gz
    checksum: md5:08dcaddba49647fc1b126ae5d4c2749a
  when: ansible_distribution == "Ubuntu"

- name: "删除 /usr/local/software/VSCode-linux-x64"
  file:
    path: /usr/local/software/VSCode-linux-x64
    state: absent

- name: "解压vscode到目录/usr/local/software"
  shell: tar -xvzf /tmp/code-stable-x64-1694670691.tar.gz -C /usr/local/software
  when: ansible_distribution == "Ubuntu"

- copy:
    src: ./vscode.desktop
    dest: /usr/share/applications/vscode.desktop
  when: ansible_distribution == "Ubuntu"

# https://stackoverflow.com/questions/30000536/how-to-install-visual-studio-code-on-linux
- name: "创建vscode命令行快捷方式: code ."
  shell: ln -f -s /usr/local/software/VSCode-linux-x64/bin/code /usr/bin/code
  when: ansible_distribution == "Ubuntu"