---
# 安装intellJ IDEA开发工具
- file:
   name: /usr/local/software/intelliJ-IDEA
   state: directory
- stat:
   path: /usr/local/software/intelliJ-IDEA/idea-IU-201.7223.91
  register: ideaFolderVar
- get_url:
   url: https://bucketxyh.oss-cn-hongkong.aliyuncs.com/intelliJ-IDEA/ideaIU-2020.1.1.tar.gz
   dest: /usr/local/software/intelliJ-IDEA/ideaIU-2020.1.1.tar.gz
  when: not ideaFolderVar.stat.exists
- shell: cd /usr/local/software/intelliJ-IDEA && tar -xvzf ideaIU-2020.1.1.tar.gz
  when: not ideaFolderVar.stat.exists
- file:
   name: /usr/local/software/intelliJ-IDEA/ideaIU-2020.1.1.tar.gz
   state: absent
- find:
   paths: /home
   file_type: directory
  register: varFiles
- file:
   name: /home/{{ item.path.split('/').2 }}/.m2
   state: directory
  with_items:
    - "{{ varFiles.files }}"
- copy:
   src: ./settings.xml
   dest: /home/{{ item.path.split('/').2 }}/.m2/settings.xml
  with_items:
    - "{{ varFiles.files }}"
- file:
   path: /home/{{ item.path.split('/').2 }}/.m2
   group: "{{ item.path.split('/').2 }}"
   owner: "{{ item.path.split('/').2 }}"
   recurse: yes
  with_items:
    - "{{ varFiles.files }}"

- name: "下载jetbrains-agent.jar到用户目录"
  get_url:
    url: https://bucketxyh.oss-cn-hongkong.aliyuncs.com/intelliJ-IDEA/jetbrains-agent.jar
    dest: /usr/local/software/intelliJ-IDEA/idea-IU-201.7223.91/jetbrains-agent.jar

- copy:
   src: ./idea.desktop
   dest: /usr/share/applications/idea.desktop
