---
# 安装intellJ IDEA开发工具
- file:
   name: /usr/local/software/intelliJ-IDEA
   state: directory
- stat:
   path: /usr/local/software/intelliJ-IDEA/idea-IU-201.7223.91
  register: ideaFolderVar
- get_url:
   url: https://bucketxyh.oss-cn-hongkong.aliyuncs.com/intelliJ-IDEA/ideaIU-2020.1.1.tar.gz
   dest: /usr/local/software/intelliJ-IDEA/ideaIU-2020.1.1.tar.gz
  when: not ideaFolderVar.stat.exists
- shell: cd /usr/local/software/intelliJ-IDEA && tar -xvzf ideaIU-2020.1.1.tar.gz
  when: not ideaFolderVar.stat.exists
- file:
   name: /usr/local/software/intelliJ-IDEA/ideaIU-2020.1.1.tar.gz
   state: absent
- file:
   name: /home/{{ lookup('env', 'USER') }}/.m2
   state: directory
- copy:
   src: ./settings.xml
   dest: /home/{{ lookup('env', 'USER') }}/.m2/settings.xml

- name: "下载jetbrains-agent.jar到用户目录"
  get_url:
    url: https://bucketxyh.oss-cn-hongkong.aliyuncs.com/intelliJ-IDEA/jetbrains-agent.jar
    dest: /home/{{ lookup('env', 'USER') }}/jetbrains-agent.jar
