- name: "判断操作支持的操作系统"
  assert:
    that:
      - ansible_distribution == "Ubuntu" or (ansible_distribution == "CentOS" and ansible_distribution_major_version == "8")
    fail_msg: "docker目前只支持ubuntu、centOS8系统安装"

- package_facts:
   manager: auto
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

- name: "保证unzip命令已经安装"
  yum:
    name: unzip
    state: installed

# centOS安装docker
- name: "yum install yum-utils -y"
  yum:
    name: yum-utils
    state: installed
  when: ansible_distribution == "CentOS"

- name: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_distribution == "CentOS"

- name: "yum remove podman-manpages"
  yum:
    name: podman-manpages
    state: removed
  when: ansible_distribution == "CentOS"
- name: "yum remove podman"
  yum:
    name: podman
    state: removed
  when: ansible_distribution == "CentOS"

# centOS8下载和安装docker-ce
- name: "下载docker-23.0.5-1-rpms.zip到目录/tmp"
  get_url:
    url: https://bucketxyh.oss-cn-hongkong.aliyuncs.com/docker/docker-23.0.5-1-rpms.zip
    dest: /tmp/docker-23.0.5-1-rpms.zip
    checksum: md5:4e08a727cd89b9f7ea33a4de5464723b
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

- name: "解压/tmp/docker-23.0.5-1-rpms.zip到/tmp/docker-23.0.5-1-rpms"
  shell: unzip /tmp/docker-23.0.5-1-rpms.zip -d /tmp/docker-23.0.5-1-rpms
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

- name: "使用yum命令安装docker"
  shell: cd /tmp/docker-23.0.5-1-rpms && yum install -y *.rpm --allowerasing
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8" and 'docker' not in ansible_facts.packages

# NOTE: 不再支持centOS7安装docker
## centOS7下载和安装docker-ce
#- name: "centOS7下载docker-ce rpm安装程序"
#  get_url:
#    url: https://bucketxy.oss-cn-hangzhou.aliyuncs.com/docker/docker-ce-20.10.6-3.el7.x86_64.rpm
#    dest: /tmp/docker-ce-20.10.6-3.el7.x86_64.rpm
#    checksum: md5:4004a06a68002e59797264fce3c9defe
#  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
#- name: "centOS7安装docker-ce"
#  yum:
#    name: /tmp/docker-ce-20.10.6-3.el7.x86_64.rpm
#    state: installed
#  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

# ubuntu安装docker参考
# https://docs.docker.com/engine/install/ubuntu/
- name: "卸载旧版本docker"
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  when: ansible_distribution == "Ubuntu"

- name: "执行apt-get update"
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: "卸载系统已安装的libcurl4"
  apt:
    name: libcurl4
    state: absent
  when: ansible_distribution == "Ubuntu"
- name: "安装相关组件允许apt使用HTTPS和仓库通讯"
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  when: ansible_distribution == "Ubuntu"

- name: "添加docker官方GPG key"
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --yes --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  when: ansible_distribution == "Ubuntu"

- name: "添加docker官方仓库"
  shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: ansible_distribution == "Ubuntu"

- name: "执行apt-get update"
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

#- name: "安装docker相关组件"
#  apt:
#    name:
#      - docker-ce=5:20.10.6~3-0~ubuntu-focal
#      - docker-ce-cli=5:20.10.6~3-0~ubuntu-focal
#      - containerd.io
#    state: present
#  when: ansible_distribution == "Ubuntu"

- name: "下载docker-23.0.5-1-debs.zip到目录/tmp"
  get_url:
    url: https://bucketxyh.oss-cn-hongkong.aliyuncs.com/docker/docker-23.0.5-1-debs.zip
    dest: /tmp/docker-23.0.5-1-debs.zip
    checksum: md5:f87a10921ca90ad87c0dcd42e8c9fde5
  when: ansible_distribution == "Ubuntu"

- name: "解压/tmp/docker-23.0.5-1-debs.zip到/tmp/docker-23.0.5-1-debs"
  shell: unzip /tmp/docker-23.0.5-1-debs.zip -d /tmp/docker-23.0.5-1-debs
  when: ansible_distribution == "Ubuntu"

- name: "使用dpkg命令安装docker"
  shell: cd /tmp/docker-23.0.5-1-debs && dpkg -i *.deb
  when: ansible_distribution == "Ubuntu"

# 把当前用户添加到docker用户组，否则在使用docker-compose时会报告permission denied错误
# https://www.linuxrumen.com/rmxx/1665.html
# 获取/home目录下的子目录
- find:
   paths: /home
   file_type: directory
  register: varFiles
- shell: usermod -aG docker {{ item.path.split('/').2 }}
  with_items:
   - "{{ varFiles.files }}"
  when: ansible_distribution == "Ubuntu"

- name: "mkdir -p /etc/docker"
  shell: mkdir -p /etc/docker
  ignore_errors: yes
  when: ansible_distribution == "CentOS"

- name: "copy daemon.json to /etc/docker/daemon.json"
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: "systemctl enable docker and systemctl start docker"
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: "Download docker-compose-Linux-x86_64"
  get_url:
   url: https://bucketxyh.oss-cn-hongkong.aliyuncs.com/docker/docker-compose-Linux-x86_64
   dest: /tmp/docker-compose-Linux-x86_64
   checksum: md5:8f68ae5d2334eecb0ee50b809b5cec58
- name: "cp /tmp/docker-compose-Linux-x86_64 /usr/local/bin/docker-compose"
  shell: cp /tmp/docker-compose-Linux-x86_64 /usr/local/bin/docker-compose
- name: "ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose"
  shell: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  ignore_errors: yes
- name: "chmod +x /usr/local/bin/docker-compose"
  shell: chmod +x /usr/local/bin/docker-compose