- name: "判断是否支持当前操作系统"
  assert:
    that:
      - ansible_distribution == "Ubuntu"
    fail_msg: "selenium目前只支持Ubuntu系统部署"

- name: "安装selenium"
  pip:
    name: selenium
    version: 4.0.0
    state: present

- name: "下载firefox geckodriver"
  get_url:
    url: https://bucketxyh.oss-cn-hongkong.aliyuncs.com/browserdriver/geckodriver-v0.31.0-linux64.tar.gz
    dest: /tmp/geckodriver-v0.31.0-linux64.tar.gz
    checksum: md5:eac7c4af356668ab9acb7d16c843c62f

- name: "解压firefox geckodriver"
  shell: cd /tmp && tar -xvzf geckodriver-v0.31.0-linux64.tar.gz

- name: "复制geckodriver到/usr/bin"
  copy:
    src: /tmp/geckodriver
    dest: /usr/bin/geckodriver
    force: yes
    remote_src: yes
    mode: 0755

# https://chromedriver.chromium.org/downloads
- name: "下载chromedriver"
  get_url:
    url: https://bucketxyh.oss-cn-hongkong.aliyuncs.com/selenium/chromedriver-108
    dest: /tmp/chromedriver-108
    checksum: md5:f0e0037f3b18de2196af7c19f5b8b0c1

- name: "复制chromedriver到/usr/bin"
  copy:
    src: /tmp/chromedriver-108
    dest: /usr/bin/chromedriver
    force: yes
    remote_src: yes
    mode: 0755