---
- package_facts:
   manager: auto
  when: ansible_distribution == "CentOS"

# 判断是否已安装java
# 参考 https://stackoverflow.com/questions/30388361/ansible-command-to-check-the-java-version-in-different-servers
- name: "判断是否已安装java"
  command: java -version
  register: var_java_version
  ignore_errors: true

# centOS安装jdk
- name: 下载jdk rpm
  get_url:
   url: http://bucketxy.cn-gd.ufileos.com/jdk/jdk-8u144-linux-x64.rpm
   dest: /tmp/jdk-8u144-linux-x64.rpm
  when: var_java_version is failed and ansible_distribution == "CentOS" and "jdk1.8.0_144" not in ansible_facts.packages

- name: 安装jdk
  yum:
   name: /tmp/jdk-8u144-linux-x64.rpm
   state: installed
   disable_gpg_check: yes
  when: var_java_version is failed and ansible_distribution == "CentOS" and "jdk1.8.0_144" not in ansible_facts.packages

# debian10、ubuntu安装和配置jdk
- stat: path=/usr/local/jdk1.8.0_271
  register: var_folder_jdk
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: "下载jdk-8u271-linux-x64.tar.gz"
  get_url:
   url: http://bucketxy.cn-gd.ufileos.com/jdk/jdk-8u271-linux-x64.tar.gz
   dest: /tmp/jdk-8u271-linux-x64.tar.gz
   checksum: md5:bd8dc95a810b095996acf5f5b0dd2a69
  when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu") and not var_folder_jdk.stat.exists

- name: "解压/tmp/jdk-8u271-linux-x64.tar.gz到/usr/local目录"
  shell: tar -xvzf /tmp/jdk-8u271-linux-x64.tar.gz -C /usr/local
  when: (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu") and not var_folder_jdk.stat.exists

- name: "复制文件初始化java环境变量jdk.sh到/etc/profile.d/jdk.sh"
  copy:
    src: jdk.sh
    dest: /etc/profile.d/jdk.sh
    force: no
  when: var_java_version is failed and (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")

- name: "执行update-alternatives --install '/usr/bin/java' 'java' '/usr/local/jdk1.8.0_271/bin/java' 1500"
  shell: update-alternatives --install "/usr/bin/java" "java" "/usr/local/jdk1.8.0_271/bin/java" 1500
  when: var_java_version is failed and (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")

- name: "执行update-alternatives --install '/usr/bin/javac' 'javac' '/usr/local/jdk1.8.0_271/bin/javac' 1500"
  shell: update-alternatives --install "/usr/bin/javac" "javac" "/usr/local/jdk1.8.0_271/bin/javac" 1500
  when: var_java_version is failed and (ansible_distribution == "Debian" or ansible_distribution == "Ubuntu")

- file:
   path: /tmp/jdk-8u144-linux-x64.rpm
   state: absent