- name: "下载zookeeper-3.4.9.tar.gz"
  get_url:
    url: https://bucketxy.oss-cn-hangzhou.aliyuncs.com/zookeeper/zookeeper-3.4.9.tar.gz
    dest: /tmp/zookeeper-3.4.9.tar.gz
    checksum: md5:3e8506075212c2d41030d874fcc9dcd2

- name: "cd /tmp && tar -xvzf zookeeper-3.4.9.tar.gz"
  shell: cd /tmp && tar -xvzf zookeeper-3.4.9.tar.gz

- name: "创建/data目录"
  file:
    path: /data
    state: directory

- name: "mv -n /tmp/zookeeper-3.4.9 /data"
  shell: mv -n /tmp/zookeeper-3.4.9 /data

- name: "复制zoo.cfg到/data/zookeeper-3.4.9/conf/zoo.cfg"
  template:
    src: zoo_sample.cfg
    dest: /data/zookeeper-3.4.9/conf/zoo.cfg

- name: "cd /data/zookeeper-3.4.9/bin && sh zkServer.sh start"
  shell: cd /data/zookeeper-3.4.9/bin && sh zkServer.sh start

# 设置zookeeper rc.local
- name: "设置zookeeper rc.local"
  lineinfile:
    path: /etc/rc.d/rc.local
    regexp: "^sudo -i sh -c \"cd /data/zookeeper-3.4.9/bin && sh zkServer.sh start\""
    line: "sudo -i sh -c \"cd /data/zookeeper-3.4.9/bin && sh zkServer.sh start\""

