# Install necessary compile component
- name: "yum install make readline-devel pcre-devel openssl-devel gcc perl"
  yum:
    name: make,readline-devel,pcre-devel,openssl-devel,gcc,perl
    state: installed

- name: "从http://bucketxy.cn-gd.ufileos.com/nginx/openresty-1.15.8.1.tar.gz下载openresty源代码"
  get_url:
    url: http://bucketxy.cn-gd.ufileos.com/nginx/openresty-1.15.8.1.tar.gz
    dest: /tmp/openresty-1.15.8.1.tar.gz
    checksum: md5:d614e17360e3a805ff94edbf7037221c
- name: "从http://bucketxy.cn-gd.ufileos.com/nginx/naxsi-0.56.tar.gz下载naxsi源代码"
  get_url:
    url: http://bucketxy.cn-gd.ufileos.com/nginx/naxsi-0.56.tar.gz
    dest: /tmp/naxsi-0.56.tar.gz
    checksum: md5:01a28913b57dfce2ab8435b56d292f82

- name: "删除目录/tmp/openresty-1.15.8.1"
  file:
    path: /tmp/openresty-1.15.8.1
    state: absent
- name: "删除目录/tmp/naxsi-0.56"
  file:
    path: /tmp/naxsi-0.56
    state: absent
- name: "删除目录/usr/local/openresty"
  file:
    path: /usr/local/openresty
    state: absent
- name: "删除文件/usr/local/openresty.tar.gz"
  file:
    path: /usr/local/openresty.tar.gz
    state: absent

- name: "cd /tmp && tar -xzf openresty-1.15.8.1.tar.gz"
  shell: cd /tmp && tar -xzf openresty-1.15.8.1.tar.gz
- name: "cd /tmp && tar -xzf naxsi-0.56.tar.gz"
  shell: cd /tmp && tar -xzf naxsi-0.56.tar.gz

- name: "cd /tmp/openresty-1.15.8.1 && ./configure --add-module=/tmp/naxsi-0.56/naxsi_src --with-http_v2_module"
  shell: cd /tmp/openresty-1.15.8.1 && ./configure --add-module=/tmp/naxsi-0.56/naxsi_src --with-http_v2_module
- name: "cd /tmp/openresty-1.15.8.1 && make install"
  shell: cd /tmp/openresty-1.15.8.1 && make install

- name: "cp -nf /tmp/naxsi-0.56/naxsi_config/naxsi_core.rules /usr/local/openresty/nginx/conf/naxsi_core.rules"
  shell: cp -nf /tmp/naxsi-0.56/naxsi_config/naxsi_core.rules /usr/local/openresty/nginx/conf/naxsi_core.rules

# 删除默认的 /usr/local/openresty/nginx/conf/default.conf 文件
# 因为在openresty部署时会先备份 default.conf 文件，如果存在默认 default.conf 文件在首次部署时会被备份为 default.conf.bak 文件
# 最终会影响真正的 default.conf 文件备份
- name: "删除默认的 /usr/local/openresty/nginx/conf/default.conf 文件"
  file:
    path: /usr/local/openresty/nginx/conf/default.conf
    state: absent

- name: "cd /usr/local/ && tar -czf openresty.tar.gz openresty/*"
  shell: cd /usr/local/ && tar -czf openresty.tar.gz openresty/*

- yum:
   name: rsync
   state: installed
- name: "复制openresty.tar.gz到本地目录/tmp"
  synchronize:
   src: /usr/local/openresty.tar.gz
   dest: /tmp/openresty.tar.gz
   mode: pull